apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-yrbx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-yrbx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0011-app
  name: devfile-sample-yrbx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-yrbx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-yrbx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-yrbx@sha256:a0f183bf46a5af7ab852bd59844581caa3b0f7ced8a4f55df05e9ba60a736e9b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
